Update whatsystem

diff --git a/whatsystem b/whatsystem
--- a/whatsystem
+++ b/whatsystem
@@ -26,6 +26,10 @@ if [ -z "$direccion" ]; then
 	echo "[!] Ejemplo de uso: $0 192.168.1.32"
     exit 1
 fi
+if [[ ! "$direccion" =~ ^[a-zA-Z0-9.-]+$ ]]; then
+    echo "[-] Error: Caracteres no permitidos en la dirección IP o dominio."
+    exit 1
+fi
 ttl=$(ping -c 1 "$direccion" | grep -oP 'ttl=\K\d+')
 if [ -z "$ttl" ]; then
     echo "[-] Host inalcanzable."
